#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    password: 1234
#    username: postgres
#    url: jdbc:postgresql://localhost:5432/Test
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    format_sql: true
#  liquibase:
#    change-log: classpath:db/changelog/change-log-root.yaml
#    enable: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_judo
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/change-log-root.yaml
